# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user = User.create(email:"a@a.com", password: 'asdfASDF1')
user.posts.create(blog_entry: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vehicula nunc in lorem vestibulum, id ornare sem faucibus. Nunc tincidunt sem vel nisl vehicula feugiat ac id nibh. Maecenas laoreet a leo sit amet euismod. Morbi eget nibh ultricies, finibus ipsum eget, sollicitudin mi. Aenean eget purus id lectus aliquet dictum quis suscipit justo. Curabitur elit sapien, fringilla a ullamcorper nec, pretium sed mi. Nunc pellentesque porttitor nisi vitae facilisis. Morbi sed lorem turpis. Pellentesque pulvinar libero id nibh ultrices, et commodo risus mollis. Morbi ornare, justo nec congue gravida, metus augue commodo odio, in ullamcorper erat ante in neque. Curabitur sed pharetra magna, non placerat risus. Etiam sed ipsum sem. Nunc sed rhoncus magna.')
user.posts.create(blog_entry: 'Quisque blandit, massa at consequat interdum, diam dui consequat enim, ac iaculis velit risus vitae lacus. Mauris dictum commodo arcu accumsan dignissim. Cras consequat fermentum fringilla. Curabitur sed ipsum suscipit, mollis augue eget, posuere tortor. Praesent commodo nisi non sem tristique, ut commodo lacus dapibus. Vivamus euismod tempus ligula quis congue. Ut commodo sit amet ex vel placerat. Duis pulvinar molestie sem ac aliquet. Nam tempus sed purus ac lacinia. Nullam tincidunt elit quis magna maximus pretium at vel enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
user.posts.create(blog_entry: 'Integer finibus gravida iaculis. Nulla viverra consectetur sem, id elementum risus euismod vel. Nullam in luctus dolor. Morbi erat eros, condimentum et risus suscipit, tempus lacinia nisi. In ut urna sollicitudin, consequat libero et, porta quam. Nullam ac libero ut urna dictum vehicula. Nam tincidunt dui vel ultrices elementum. Mauris malesuada eros suscipit odio dictum aliquam. Nam suscipit venenatis purus eu imperdiet. Duis egestas erat vel cursus auctor. Sed lacinia finibus egestas.')